version: "3.3"
services:
  redis:
    image: redis:7.0.4-alpine
    container_name: redis_example
    restart: always
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: